# This file represents `spec.parameters.objects` of [SecretProviderClass]
# (https://docs.aws.amazon.com/secretsmanager/latest/userguide/integrating_csi_driver.html#integrating_csi_driver_SecretProviderClass)
- objectName: "ARN OF THE SECRET OBJECT, which has username and password as objects as example"
  jmesPath: 
    - path: username
      objectAlias: dbusername
    - path: password
      objectAlias: dbpassword
- objectName: "ARN OF THE OTHER SECRET OBJECT"

        